/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalatRouteImport } from './routes/salat'
import { Route as LeadpilotRouteImport } from './routes/leadpilot'
import { Route as DesignerOsRouteImport } from './routes/designer-os'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsDesignerOsRouteImport } from './routes/extensions.designer-os'

const SalatRoute = SalatRouteImport.update({
  id: '/salat',
  path: '/salat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadpilotRoute = LeadpilotRouteImport.update({
  id: '/leadpilot',
  path: '/leadpilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerOsRoute = DesignerOsRouteImport.update({
  id: '/designer-os',
  path: '/designer-os',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsDesignerOsRoute = ExtensionsDesignerOsRouteImport.update({
  id: '/extensions/designer-os',
  path: '/extensions/designer-os',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer-os': typeof DesignerOsRoute
  '/leadpilot': typeof LeadpilotRoute
  '/salat': typeof SalatRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer-os': typeof DesignerOsRoute
  '/leadpilot': typeof LeadpilotRoute
  '/salat': typeof SalatRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer-os': typeof DesignerOsRoute
  '/leadpilot': typeof LeadpilotRoute
  '/salat': typeof SalatRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/designer-os'
    | '/leadpilot'
    | '/salat'
    | '/extensions/designer-os'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designer-os' | '/leadpilot' | '/salat' | '/extensions/designer-os'
  id:
    | '__root__'
    | '/'
    | '/designer-os'
    | '/leadpilot'
    | '/salat'
    | '/extensions/designer-os'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerOsRoute: typeof DesignerOsRoute
  LeadpilotRoute: typeof LeadpilotRoute
  SalatRoute: typeof SalatRoute
  ExtensionsDesignerOsRoute: typeof ExtensionsDesignerOsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salat': {
      id: '/salat'
      path: '/salat'
      fullPath: '/salat'
      preLoaderRoute: typeof SalatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadpilot': {
      id: '/leadpilot'
      path: '/leadpilot'
      fullPath: '/leadpilot'
      preLoaderRoute: typeof LeadpilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer-os': {
      id: '/designer-os'
      path: '/designer-os'
      fullPath: '/designer-os'
      preLoaderRoute: typeof DesignerOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/designer-os': {
      id: '/extensions/designer-os'
      path: '/extensions/designer-os'
      fullPath: '/extensions/designer-os'
      preLoaderRoute: typeof ExtensionsDesignerOsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerOsRoute: DesignerOsRoute,
  LeadpilotRoute: LeadpilotRoute,
  SalatRoute: SalatRoute,
  ExtensionsDesignerOsRoute: ExtensionsDesignerOsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
