/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewtabPreviewRouteImport } from './routes/newtab-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsDesignerOsRouteImport } from './routes/extensions.designer-os'

const NewtabPreviewRoute = NewtabPreviewRouteImport.update({
  id: '/newtab-preview',
  path: '/newtab-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsDesignerOsRoute = ExtensionsDesignerOsRouteImport.update({
  id: '/extensions/designer-os',
  path: '/extensions/designer-os',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
  '/extensions/designer-os': typeof ExtensionsDesignerOsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newtab-preview' | '/extensions/designer-os'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newtab-preview' | '/extensions/designer-os'
  id: '__root__' | '/' | '/newtab-preview' | '/extensions/designer-os'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewtabPreviewRoute: typeof NewtabPreviewRoute
  ExtensionsDesignerOsRoute: typeof ExtensionsDesignerOsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newtab-preview': {
      id: '/newtab-preview'
      path: '/newtab-preview'
      fullPath: '/newtab-preview'
      preLoaderRoute: typeof NewtabPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/designer-os': {
      id: '/extensions/designer-os'
      path: '/extensions/designer-os'
      fullPath: '/extensions/designer-os'
      preLoaderRoute: typeof ExtensionsDesignerOsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewtabPreviewRoute: NewtabPreviewRoute,
  ExtensionsDesignerOsRoute: ExtensionsDesignerOsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
