/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewtabPreviewRouteImport } from './routes/newtab-preview'
import { Route as IndexRouteImport } from './routes/index'

const NewtabPreviewRoute = NewtabPreviewRouteImport.update({
  id: '/newtab-preview',
  path: '/newtab-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/newtab-preview': typeof NewtabPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/newtab-preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/newtab-preview'
  id: '__root__' | '/' | '/newtab-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewtabPreviewRoute: typeof NewtabPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/newtab-preview': {
      id: '/newtab-preview'
      path: '/newtab-preview'
      fullPath: '/newtab-preview'
      preLoaderRoute: typeof NewtabPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewtabPreviewRoute: NewtabPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
